### ISSUE TITLE
Exercício de Arrays

### ISSUE THREAD

**Issue by angelogluz** [angelogluz/ES6#2]
## Pré requisitos (Dependências)

[ESLint](https://eslint.org/) - Code style AirBnB

[Editor Config for VSCode](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig)

[Faker](https://github.com/marak/Faker.js/)

## Cenário

Tratar o conteúdo de um array com 1.000 registros através de <code> map, filter, reduce, find e outras possíveis funções </code> funções.

Campos dos objetos objetos que irão compor o array: <code> name, birthday, genre, lastpurchase, countpurchase </code>

## Desafios

0. Mockar a criação dos objetos respeitando os seguintes requisitos:
- Os dados devem estar em pt_BR;
- Os dados devem ser coerentes com os seus campos. Ex: é impossível que algum cliente tenha nascido em 2022;
- As datas de nascimento devem ser entre 1910 a 2019.
- Os nomes devem ser nomes completos.

1. Desenvolva, utilizando <code> filter </code>, uma função que, dado um caractere de entrada, retorne todos os registros de clientes cujo o nome inicia com o caractere.

2. Retorne o array de clientes 

3. Desenvolva uma função que, dado o caractere de entrada, retorna apenas um número com o total de registros encontrados.

4. Desenvolva uma função que retorne apenas os nomes dos clientes.

5. Desenvolva uma função que retorne apenas o primeiro nome dos clientes.

6. Desenvolva uma função que retorne apenas o primeiro nome dos clientes cujo os nomes começam com o caractere de entrada da função.

7. Desenvolva uma função que retorne todos os usuários que são maiores de idade.

8. Desenvolva uma função que, dado um nome de entrada, retorna se o nome está contido na lista.

9. Implemente uma função que retorna o total de vendas realizadas somando as compras de todos os clientes.

10. Implemente uma função que retorne os dados dos clientes que não compram há mais de 1 ano.

11. Implemente uma função que retorne os dados dos clientes que já realizaram mais de 15 compras.

## Entrega

Suba sua solução em um repositório público e adicione nos comentários o link para o mesmo.

**Comment by uilianbarbosa** [comment]
https://gitlab.com/uilianbarbosa/es3_arrow_functions

**Comment by Mkroning** [comment]
https://github.com/Mkroning/Algoritmo-e-Programa-o-3

**Comment by almeidasenac** [comment]
https://github.com/almeidasenac/Exercicio-de-Arrays-2

**Comment by chioato-leticia** [comment]
https://github.com/chioato-leticia/senac-ESIII

**Comment by lazaroap** [comment]
https://github.com/lazaroap/ES3

**Comment by Fumagalli** [comment]
https://github.com/Fumagalli/arrays2

**Comment by luizpicoli** [comment]
https://gitlab.com/felipepicoli/arrays-em-js

**Comment by natanielporto** [comment]
https://github.com/natanielporto/engenhariadesoftwareIII

**Comment by lucasrutz** [comment]
https://gitlab.com/lucasrutz/arrow_functions

**Comment by ThaisRK** [comment]
https://gitlab.com/ThaisRK/es3/-/blob/master/exemplos_exercicios/desafio.js

**Comment by bernardok9** [comment]
https://github.com/bernardok9/ES6

**Comment by guigopel** [comment]
https://github.com/guigopel/manipulacaoArrays

**Comment by almeidasenac** [comment]
https://github.com/almeidasenac/Exercicios
